name: Test Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Test build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Test the build
          nix build .#shrimp-batcher --impure --show-trace
