name: Update Shrimp Batcher

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours



jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release info

        id: release
        # For gh cli
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Get latest release info
          LATEST_RELEASE=$(gh release view --repo centroid-is/blossom --json tagName,assets)
          
          # Extract version (removing 'v' prefix if it exists)
          VERSION=$(echo "$LATEST_RELEASE" | jq -r '.tagName' | sed 's/^v//')
          
          # Find the asset URL for shrimp-batcher.tar.gz
          ASSET_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name=="shrimp-batcher.tar.gz") | .apiUrl')
          
          # Get current version from Nix file
          CURRENT_VERSION=$(grep 'version = ' packages/shrimp-batcher/default.nix | cut -d'"' -f2)
          
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT
          echo "asset_url=$ASSET_URL" >> $GITHUB_OUTPUT

      - name: Update Nix file
        if: steps.release.outputs.current_version != steps.release.outputs.new_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ steps.release.outputs.new_version }}
          ASSET_URL: ${{ steps.release.outputs.asset_url }}
        run: |
          # Download the asset to calculate its hash
          curl -L -H "Accept: application/octet-stream" \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               "$ASSET_URL" \
               -o shrimp-batcher.tar.gz

          # Calculate SHA256 hash and convert to base32
          NEW_HASH=$(sha256sum shrimp-batcher.tar.gz | cut -d' ' -f1 | xxd -r -p | basenc --base32 | tr -d '=' | tr '[:upper:]' '[:lower:]')

          # Update the Nix file
          sed -i "s/version = \".*\"/version = \"$NEW_VERSION\"/" packages/shrimp-batcher/default.nix
          sed -i "s|https://api.github.com/repos/centroid-is/blossom/releases/assets/[0-9]\\+|$ASSET_URL|" packages/shrimp-batcher/default.nix
          sed -i "s/sha256 = \"sha256-[^\"]*\"/sha256 = \"sha256-$NEW_HASH\"/" packages/shrimp-batcher/default.nix

          # Clean up the downloaded file
          rm shrimp-batcher.tar.gz

      - name: Create Pull Request
        if: steps.release.outputs.current_version != steps.release.outputs.new_version
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update shrimp-batcher to ${{ steps.release.outputs.new_version }}"
          title: "Update shrimp-batcher to ${{ steps.release.outputs.new_version }}"
          body: |
            Updates shrimp-batcher from ${{ steps.release.outputs.current_version }} to ${{ steps.release.outputs.new_version }}
            
            - Updates version
            - Updates asset URL
            - Updates SHA256 hash
            
            This PR was automatically generated by the update-shrimp-batcher workflow.
          branch: update-shrimp-batcher
          delete-branch: true 